### PR TITLE
Fix/null resource

### PR DESCRIPTION
**Pull request by DTherHtun**
add parameter --platform managed at null_resource

### CODE REVIEW

**Comment by scottwinkler** [comment]
Hello @DTherHtun, thank you for your pull request. I am currently finishing up edits to chapter 7.  I reworked much of the scenario. There were some major changes to the GCP provider from the time that I wrote the chapter until now. I believe the revised scenario will be easier to follow and deploy. Unfortunately, this new version will take a few weeks before it gets released.

As for what is currently deployed, yes this code is necessary and so I will approve the pull request for that. I am also aware that there is an error that is preventing the Terraform code from applying. Cloud Run now returns an error if there isn't already an image in the Container Registry which means that the container has to be deployed before the apply will succeed. If you like, I can send you a PDF of my current pre-released draft that has a workaround for this.

Thanks,
Scott

**Comment by DTherHtun** [comment]
Yes, I like please send to me. Thank you.

**Comment by scottwinkler** [comment]
Here you go: [chapter7.pdf](https://github.com/scottwinkler/manning-code/files/4269343/chapter7.pdf)

**Comment by DTherHtun** [comment]
Thank you

**Pull request merged**
